name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      COMPOSER_HOME: ./.composer

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF" | cut -d / -f 3 >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Test
        run: make test

      - name: Process test reports
        run: make process-reports

      - name: Package
        run: |
          make dist VERSION=${{ steps.version.outputs.contents }}
          rm -f dist/php-textile-cli.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
