name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      COMPOSER_HOME: ./.composer

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF" | cut -d / -f 3 >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Package
        run: make dist VERSION=${{ steps.version.outputs.contents }}

      - name: Changelog
        id: changelog
        run: |
          echo "contents<<CHANGELOGEOF" >> $GITHUB_OUTPUT
          sed -e '1,/##/d' -e '/##/,$d' CHANGELOG.md >> $GITHUB_OUTPUT
          echo "CHANGELOGEOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          body: ${{ steps.changelog.outputs.contents }}

      - name: Upload package
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/php-textile-cli.zip
          asset_name: textile.zip
          asset_content_type: application/zip
