#!/usr/bin/env bash

# PHP-Textile CLI
# https://github.com/gocom/php-textile-cli
#
# Copyright (C) 2025 Jukka Svahn
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

_textile () {
    local cur prev words cword

    _init_completion || return

    case "$prev" in
        --document-root-directory)
            _filedir -d
            return
            ;;
        --image-prefix|--link-prefix)
            COMPREPLY=($(compgen -W 'http:// https://' -- "$cur"))
            return;
            ;;
        --link-relation-ship)
            COMPREPLY=($(compgen -W 'nofollow noreferrer' -- "$cur"))
            return;
            ;;
        -o|--output)
            _filedir
            return
            ;;
    esac

    case "$cur" in
        -*)
            COMPREPLY=($(compgen -W '$( _parse_help "$1" | sed "s/=//" )' -- "$cur"))
            return
            ;;
        *)
            _filedir
            return
            ;;
    esac
} && complete -F _textile textile
